// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/games/games.proto

package gamespb

import (
	engine "github.com/laerson/mancala/proto/engine"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         *engine.GameState      `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Player1Id     string                 `protobuf:"bytes,3,opt,name=player1_id,json=player1Id,proto3" json:"player1_id,omitempty"`
	Player2Id     string                 `protobuf:"bytes,4,opt,name=player2_id,json=player2Id,proto3" json:"player2_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_proto_games_games_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_games_games_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_games_games_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetState() *engine.GameState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Game) GetPlayer1Id() string {
	if x != nil {
		return x.Player1Id
	}
	return ""
}

func (x *Game) GetPlayer2Id() string {
	if x != nil {
		return x.Player2Id
	}
	return ""
}

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player1Id     string                 `protobuf:"bytes,1,opt,name=player1_id,json=player1Id,proto3" json:"player1_id,omitempty"`
	Player2Id     string                 `protobuf:"bytes,2,opt,name=player2_id,json=player2Id,proto3" json:"player2_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_proto_games_games_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_games_games_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_games_games_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameRequest) GetPlayer1Id() string {
	if x != nil {
		return x.Player1Id
	}
	return ""
}

func (x *CreateGameRequest) GetPlayer2Id() string {
	if x != nil {
		return x.Player2Id
	}
	return ""
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_proto_games_games_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_games_games_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_games_games_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type MakeGameMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PitIndex      uint32                 `protobuf:"varint,3,opt,name=pit_index,json=pitIndex,proto3" json:"pit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeGameMoveRequest) Reset() {
	*x = MakeGameMoveRequest{}
	mi := &file_proto_games_games_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeGameMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeGameMoveRequest) ProtoMessage() {}

func (x *MakeGameMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_games_games_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeGameMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeGameMoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_games_games_proto_rawDescGZIP(), []int{3}
}

func (x *MakeGameMoveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MakeGameMoveRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MakeGameMoveRequest) GetPitIndex() uint32 {
	if x != nil {
		return x.PitIndex
	}
	return 0
}

type MakeGameMoveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*MakeGameMoveResponse_MoveResult
	//	*MakeGameMoveResponse_Error
	Result        isMakeGameMoveResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeGameMoveResponse) Reset() {
	*x = MakeGameMoveResponse{}
	mi := &file_proto_games_games_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeGameMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeGameMoveResponse) ProtoMessage() {}

func (x *MakeGameMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_games_games_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeGameMoveResponse.ProtoReflect.Descriptor instead.
func (*MakeGameMoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_games_games_proto_rawDescGZIP(), []int{4}
}

func (x *MakeGameMoveResponse) GetResult() isMakeGameMoveResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MakeGameMoveResponse) GetMoveResult() *engine.MoveResult {
	if x != nil {
		if x, ok := x.Result.(*MakeGameMoveResponse_MoveResult); ok {
			return x.MoveResult
		}
	}
	return nil
}

func (x *MakeGameMoveResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*MakeGameMoveResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isMakeGameMoveResponse_Result interface {
	isMakeGameMoveResponse_Result()
}

type MakeGameMoveResponse_MoveResult struct {
	MoveResult *engine.MoveResult `protobuf:"bytes,1,opt,name=move_result,json=moveResult,proto3,oneof"`
}

type MakeGameMoveResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*MakeGameMoveResponse_MoveResult) isMakeGameMoveResponse_Result() {}

func (*MakeGameMoveResponse_Error) isMakeGameMoveResponse_Result() {}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_games_games_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_games_games_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_games_games_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_games_games_proto protoreflect.FileDescriptor

const file_proto_games_games_proto_rawDesc = "" +
	"\n" +
	"\x17proto/games/games.proto\x12\vproto.games\x1a\x19proto/engine/engine.proto\"\x83\x01\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x05state\x18\x02 \x01(\v2\x17.proto.engine.GameStateR\x05state\x12\x1d\n" +
	"\n" +
	"player1_id\x18\x03 \x01(\tR\tplayer1Id\x12\x1d\n" +
	"\n" +
	"player2_id\x18\x04 \x01(\tR\tplayer2Id\"Q\n" +
	"\x11CreateGameRequest\x12\x1d\n" +
	"\n" +
	"player1_id\x18\x01 \x01(\tR\tplayer1Id\x12\x1d\n" +
	"\n" +
	"player2_id\x18\x02 \x01(\tR\tplayer2Id\";\n" +
	"\x12CreateGameResponse\x12%\n" +
	"\x04game\x18\x01 \x01(\v2\x11.proto.games.GameR\x04game\"h\n" +
	"\x13MakeGameMoveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tpit_index\x18\x03 \x01(\rR\bpitIndex\"\x89\x01\n" +
	"\x14MakeGameMoveResponse\x12;\n" +
	"\vmove_result\x18\x01 \x01(\v2\x18.proto.engine.MoveResultH\x00R\n" +
	"moveResult\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.proto.games.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x9f\x01\n" +
	"\x05Games\x12I\n" +
	"\x06Create\x12\x1e.proto.games.CreateGameRequest\x1a\x1f.proto.games.CreateGameResponse\x12K\n" +
	"\x04Move\x12 .proto.games.MakeGameMoveRequest\x1a!.proto.games.MakeGameMoveResponseB0Z.github.com/laerson/mancala/proto/games;gamespbb\x06proto3"

var (
	file_proto_games_games_proto_rawDescOnce sync.Once
	file_proto_games_games_proto_rawDescData []byte
)

func file_proto_games_games_proto_rawDescGZIP() []byte {
	file_proto_games_games_proto_rawDescOnce.Do(func() {
		file_proto_games_games_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_games_games_proto_rawDesc), len(file_proto_games_games_proto_rawDesc)))
	})
	return file_proto_games_games_proto_rawDescData
}

var file_proto_games_games_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_games_games_proto_goTypes = []any{
	(*Game)(nil),                 // 0: proto.games.Game
	(*CreateGameRequest)(nil),    // 1: proto.games.CreateGameRequest
	(*CreateGameResponse)(nil),   // 2: proto.games.CreateGameResponse
	(*MakeGameMoveRequest)(nil),  // 3: proto.games.MakeGameMoveRequest
	(*MakeGameMoveResponse)(nil), // 4: proto.games.MakeGameMoveResponse
	(*Error)(nil),                // 5: proto.games.Error
	(*engine.GameState)(nil),     // 6: proto.engine.GameState
	(*engine.MoveResult)(nil),    // 7: proto.engine.MoveResult
}
var file_proto_games_games_proto_depIdxs = []int32{
	6, // 0: proto.games.Game.state:type_name -> proto.engine.GameState
	0, // 1: proto.games.CreateGameResponse.game:type_name -> proto.games.Game
	7, // 2: proto.games.MakeGameMoveResponse.move_result:type_name -> proto.engine.MoveResult
	5, // 3: proto.games.MakeGameMoveResponse.error:type_name -> proto.games.Error
	1, // 4: proto.games.Games.Create:input_type -> proto.games.CreateGameRequest
	3, // 5: proto.games.Games.Move:input_type -> proto.games.MakeGameMoveRequest
	2, // 6: proto.games.Games.Create:output_type -> proto.games.CreateGameResponse
	4, // 7: proto.games.Games.Move:output_type -> proto.games.MakeGameMoveResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_games_games_proto_init() }
func file_proto_games_games_proto_init() {
	if File_proto_games_games_proto != nil {
		return
	}
	file_proto_games_games_proto_msgTypes[4].OneofWrappers = []any{
		(*MakeGameMoveResponse_MoveResult)(nil),
		(*MakeGameMoveResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_games_games_proto_rawDesc), len(file_proto_games_games_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_games_games_proto_goTypes,
		DependencyIndexes: file_proto_games_games_proto_depIdxs,
		MessageInfos:      file_proto_games_games_proto_msgTypes,
	}.Build()
	File_proto_games_games_proto = out.File
	file_proto_games_games_proto_goTypes = nil
	file_proto_games_games_proto_depIdxs = nil
}
