// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/engine/engine.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player int32

const (
	Player_PLAYER_ONE Player = 0
	Player_PLAYER_TWO Player = 1
)

// Enum value maps for Player.
var (
	Player_name = map[int32]string{
		0: "PLAYER_ONE",
		1: "PLAYER_TWO",
	}
	Player_value = map[string]int32{
		"PLAYER_ONE": 0,
		"PLAYER_TWO": 1,
	}
)

func (x Player) Enum() *Player {
	p := new(Player)
	*p = x
	return p
}

func (x Player) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Player) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_engine_engine_proto_enumTypes[0].Descriptor()
}

func (Player) Type() protoreflect.EnumType {
	return &file_proto_engine_engine_proto_enumTypes[0]
}

func (x Player) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Player.Descriptor instead.
func (Player) EnumDescriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{0}
}

type Winner int32

const (
	Winner_NO_WINNER         Winner = 0
	Winner_WINNER_PLAYER_ONE Winner = 1
	Winner_WINNER_PLAYER_TWO Winner = 2
	Winner_DRAW              Winner = 3
)

// Enum value maps for Winner.
var (
	Winner_name = map[int32]string{
		0: "NO_WINNER",
		1: "WINNER_PLAYER_ONE",
		2: "WINNER_PLAYER_TWO",
		3: "DRAW",
	}
	Winner_value = map[string]int32{
		"NO_WINNER":         0,
		"WINNER_PLAYER_ONE": 1,
		"WINNER_PLAYER_TWO": 2,
		"DRAW":              3,
	}
)

func (x Winner) Enum() *Winner {
	p := new(Winner)
	*p = x
	return p
}

func (x Winner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Winner) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_engine_engine_proto_enumTypes[1].Descriptor()
}

func (Winner) Type() protoreflect.EnumType {
	return &file_proto_engine_engine_proto_enumTypes[1]
}

func (x Winner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Winner.Descriptor instead.
func (Winner) EnumDescriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{1}
}

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pits          []uint32               `protobuf:"varint,1,rep,packed,name=pits,proto3" json:"pits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_proto_engine_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetPits() []uint32 {
	if x != nil {
		return x.Pits
	}
	return nil
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	CurrentPlayer Player                 `protobuf:"varint,2,opt,name=current_player,json=currentPlayer,proto3,enum=proto.engine.Player" json:"current_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_proto_engine_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{1}
}

func (x *GameState) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GameState) GetCurrentPlayer() Player {
	if x != nil {
		return x.CurrentPlayer
	}
	return Player_PLAYER_ONE
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *GameState             `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	PitIndex      uint32                 `protobuf:"varint,2,opt,name=pit_index,json=pitIndex,proto3" json:"pit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_proto_engine_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{2}
}

func (x *MoveRequest) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *MoveRequest) GetPitIndex() uint32 {
	if x != nil {
		return x.PitIndex
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_engine_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MoveResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	CurrentPlayer Player                 `protobuf:"varint,2,opt,name=current_player,json=currentPlayer,proto3,enum=proto.engine.Player" json:"current_player,omitempty"`
	IsFinished    bool                   `protobuf:"varint,3,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	Winner        Winner                 `protobuf:"varint,4,opt,name=winner,proto3,enum=proto.engine.Winner" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResult) Reset() {
	*x = MoveResult{}
	mi := &file_proto_engine_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResult) ProtoMessage() {}

func (x *MoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResult.ProtoReflect.Descriptor instead.
func (*MoveResult) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{4}
}

func (x *MoveResult) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *MoveResult) GetCurrentPlayer() Player {
	if x != nil {
		return x.CurrentPlayer
	}
	return Player_PLAYER_ONE
}

func (x *MoveResult) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *MoveResult) GetWinner() Winner {
	if x != nil {
		return x.Winner
	}
	return Winner_NO_WINNER
}

type MoveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*MoveResponse_MoveResult
	//	*MoveResponse_Error
	Result        isMoveResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_proto_engine_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{5}
}

func (x *MoveResponse) GetResult() isMoveResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MoveResponse) GetMoveResult() *MoveResult {
	if x != nil {
		if x, ok := x.Result.(*MoveResponse_MoveResult); ok {
			return x.MoveResult
		}
	}
	return nil
}

func (x *MoveResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*MoveResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isMoveResponse_Result interface {
	isMoveResponse_Result()
}

type MoveResponse_MoveResult struct {
	MoveResult *MoveResult `protobuf:"bytes,1,opt,name=move_result,json=moveResult,proto3,oneof"`
}

type MoveResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*MoveResponse_MoveResult) isMoveResponse_Result() {}

func (*MoveResponse_Error) isMoveResponse_Result() {}

var File_proto_engine_engine_proto protoreflect.FileDescriptor

const file_proto_engine_engine_proto_rawDesc = "" +
	"\n" +
	"\x19proto/engine/engine.proto\x12\fproto.engine\"\x1b\n" +
	"\x05Board\x12\x12\n" +
	"\x04pits\x18\x01 \x03(\rR\x04pits\"s\n" +
	"\tGameState\x12)\n" +
	"\x05board\x18\x01 \x01(\v2\x13.proto.engine.BoardR\x05board\x12;\n" +
	"\x0ecurrent_player\x18\x02 \x01(\x0e2\x14.proto.engine.PlayerR\rcurrentPlayer\"b\n" +
	"\vMoveRequest\x126\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x17.proto.engine.GameStateR\tgameState\x12\x1b\n" +
	"\tpit_index\x18\x02 \x01(\rR\bpitIndex\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc3\x01\n" +
	"\n" +
	"MoveResult\x12)\n" +
	"\x05board\x18\x01 \x01(\v2\x13.proto.engine.BoardR\x05board\x12;\n" +
	"\x0ecurrent_player\x18\x02 \x01(\x0e2\x14.proto.engine.PlayerR\rcurrentPlayer\x12\x1f\n" +
	"\vis_finished\x18\x03 \x01(\bR\n" +
	"isFinished\x12,\n" +
	"\x06winner\x18\x04 \x01(\x0e2\x14.proto.engine.WinnerR\x06winner\"\x82\x01\n" +
	"\fMoveResponse\x12;\n" +
	"\vmove_result\x18\x01 \x01(\v2\x18.proto.engine.MoveResultH\x00R\n" +
	"moveResult\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.proto.engine.ErrorH\x00R\x05errorB\b\n" +
	"\x06result*(\n" +
	"\x06Player\x12\x0e\n" +
	"\n" +
	"PLAYER_ONE\x10\x00\x12\x0e\n" +
	"\n" +
	"PLAYER_TWO\x10\x01*O\n" +
	"\x06Winner\x12\r\n" +
	"\tNO_WINNER\x10\x00\x12\x15\n" +
	"\x11WINNER_PLAYER_ONE\x10\x01\x12\x15\n" +
	"\x11WINNER_PLAYER_TWO\x10\x02\x12\b\n" +
	"\x04DRAW\x10\x032G\n" +
	"\x06Engine\x12=\n" +
	"\x04Move\x12\x19.proto.engine.MoveRequest\x1a\x1a.proto.engine.MoveResponseB2Z0github.com/laerson/mancala/proto/engine;enginepbb\x06proto3"

var (
	file_proto_engine_engine_proto_rawDescOnce sync.Once
	file_proto_engine_engine_proto_rawDescData []byte
)

func file_proto_engine_engine_proto_rawDescGZIP() []byte {
	file_proto_engine_engine_proto_rawDescOnce.Do(func() {
		file_proto_engine_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engine_engine_proto_rawDesc), len(file_proto_engine_engine_proto_rawDesc)))
	})
	return file_proto_engine_engine_proto_rawDescData
}

var file_proto_engine_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_engine_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_engine_engine_proto_goTypes = []any{
	(Player)(0),          // 0: proto.engine.Player
	(Winner)(0),          // 1: proto.engine.Winner
	(*Board)(nil),        // 2: proto.engine.Board
	(*GameState)(nil),    // 3: proto.engine.GameState
	(*MoveRequest)(nil),  // 4: proto.engine.MoveRequest
	(*Error)(nil),        // 5: proto.engine.Error
	(*MoveResult)(nil),   // 6: proto.engine.MoveResult
	(*MoveResponse)(nil), // 7: proto.engine.MoveResponse
}
var file_proto_engine_engine_proto_depIdxs = []int32{
	2, // 0: proto.engine.GameState.board:type_name -> proto.engine.Board
	0, // 1: proto.engine.GameState.current_player:type_name -> proto.engine.Player
	3, // 2: proto.engine.MoveRequest.game_state:type_name -> proto.engine.GameState
	2, // 3: proto.engine.MoveResult.board:type_name -> proto.engine.Board
	0, // 4: proto.engine.MoveResult.current_player:type_name -> proto.engine.Player
	1, // 5: proto.engine.MoveResult.winner:type_name -> proto.engine.Winner
	6, // 6: proto.engine.MoveResponse.move_result:type_name -> proto.engine.MoveResult
	5, // 7: proto.engine.MoveResponse.error:type_name -> proto.engine.Error
	4, // 8: proto.engine.Engine.Move:input_type -> proto.engine.MoveRequest
	7, // 9: proto.engine.Engine.Move:output_type -> proto.engine.MoveResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_engine_engine_proto_init() }
func file_proto_engine_engine_proto_init() {
	if File_proto_engine_engine_proto != nil {
		return
	}
	file_proto_engine_engine_proto_msgTypes[5].OneofWrappers = []any{
		(*MoveResponse_MoveResult)(nil),
		(*MoveResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engine_engine_proto_rawDesc), len(file_proto_engine_engine_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_engine_engine_proto_goTypes,
		DependencyIndexes: file_proto_engine_engine_proto_depIdxs,
		EnumInfos:         file_proto_engine_engine_proto_enumTypes,
		MessageInfos:      file_proto_engine_engine_proto_msgTypes,
	}.Build()
	File_proto_engine_engine_proto = out.File
	file_proto_engine_engine_proto_goTypes = nil
	file_proto_engine_engine_proto_depIdxs = nil
}
