apiVersion: apps/v1
kind: Deployment
metadata:
  name: games
  labels:
    app: games
spec:
  replicas: 2
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name: games
        image: ghcr.io/laerson/mancala:latest-games
        ports:
        - containerPort: 50052
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: ENGINE_ADDR
          value: "engine:50051"
        - name: EVENT_BUS_ADDR
          value: "event-bus:50053"
        readinessProbe:
          tcpSocket:
            port: 50052
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 50052
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      initContainers:
      - name: wait-for-redis
        image: busybox:1.35
        command:
        - sh
        - -c
        - "until nc -z redis 6379; do echo waiting for redis; sleep 2; done"
      - name: wait-for-engine
        image: busybox:1.35
        command:
        - sh
        - -c
        - "until nc -z engine 50051; do echo waiting for engine; sleep 2; done"
      - name: wait-for-event-bus
        image: busybox:1.35
        command:
        - sh
        - -c
        - "until nc -z event-bus 50053; do echo waiting for event-bus; sleep 2; done"
---
apiVersion: v1
kind: Service
metadata:
  name: games
  labels:
    app: games
spec:
  ports:
  - port: 50052
    targetPort: 50052
    name: grpc
  selector:
    app: games
  type: ClusterIP