apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres.yaml
- redis.yaml
- engine.yaml
- games.yaml
- matchmaking.yaml
- auth.yaml
- bot.yaml

namespace: mancala

commonLabels:
  project: mancala