// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/bot/bot.proto

package botpb

import (
	engine "github.com/laerson/mancala/proto/engine"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bot difficulty levels
type BotDifficulty int32

const (
	BotDifficulty_BOT_DIFFICULTY_UNSPECIFIED BotDifficulty = 0
	BotDifficulty_BOT_DIFFICULTY_EASY        BotDifficulty = 1 // Random valid moves
	BotDifficulty_BOT_DIFFICULTY_MEDIUM      BotDifficulty = 2 // Basic strategy (captures, extra turns)
	BotDifficulty_BOT_DIFFICULTY_HARD        BotDifficulty = 3 // Advanced AI (minimax with pruning)
)

// Enum value maps for BotDifficulty.
var (
	BotDifficulty_name = map[int32]string{
		0: "BOT_DIFFICULTY_UNSPECIFIED",
		1: "BOT_DIFFICULTY_EASY",
		2: "BOT_DIFFICULTY_MEDIUM",
		3: "BOT_DIFFICULTY_HARD",
	}
	BotDifficulty_value = map[string]int32{
		"BOT_DIFFICULTY_UNSPECIFIED": 0,
		"BOT_DIFFICULTY_EASY":        1,
		"BOT_DIFFICULTY_MEDIUM":      2,
		"BOT_DIFFICULTY_HARD":        3,
	}
)

func (x BotDifficulty) Enum() *BotDifficulty {
	p := new(BotDifficulty)
	*p = x
	return p
}

func (x BotDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bot_bot_proto_enumTypes[0].Descriptor()
}

func (BotDifficulty) Type() protoreflect.EnumType {
	return &file_proto_bot_bot_proto_enumTypes[0]
}

func (x BotDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotDifficulty.Descriptor instead.
func (BotDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_proto_bot_bot_proto_rawDescGZIP(), []int{0}
}

// Bot profile information
type BotProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                               // Unique bot ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                           // Display name (e.g., "MancalaBot Easy")
	Difficulty    BotDifficulty          `protobuf:"varint,3,opt,name=difficulty,proto3,enum=proto.bot.BotDifficulty" json:"difficulty,omitempty"` // Difficulty level
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                             // Bot description
	Wins          int32                  `protobuf:"varint,5,opt,name=wins,proto3" json:"wins,omitempty"`                                          // Total wins (for display)
	Losses        int32                  `protobuf:"varint,6,opt,name=losses,proto3" json:"losses,omitempty"`                                      // Total losses (for display)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotProfile) Reset() {
	*x = BotProfile{}
	mi := &file_proto_bot_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotProfile) ProtoMessage() {}

func (x *BotProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotProfile.ProtoReflect.Descriptor instead.
func (*BotProfile) Descriptor() ([]byte, []int) {
	return file_proto_bot_bot_proto_rawDescGZIP(), []int{0}
}

func (x *BotProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BotProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BotProfile) GetDifficulty() BotDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return BotDifficulty_BOT_DIFFICULTY_UNSPECIFIED
}

func (x *BotProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BotProfile) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *BotProfile) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

// Request to get an optimal move for the bot
type GetMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *engine.GameState      `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`                // Current game state
	Difficulty    BotDifficulty          `protobuf:"varint,2,opt,name=difficulty,proto3,enum=proto.bot.BotDifficulty" json:"difficulty,omitempty"` // Bot difficulty level
	BotId         string                 `protobuf:"bytes,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`                            // Bot player ID
	TimeLimitMs   int32                  `protobuf:"varint,4,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`       // Optional: time limit for move calculation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoveRequest) Reset() {
	*x = GetMoveRequest{}
	mi := &file_proto_bot_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoveRequest) ProtoMessage() {}

func (x *GetMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoveRequest.ProtoReflect.Descriptor instead.
func (*GetMoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_bot_bot_proto_rawDescGZIP(), []int{1}
}

func (x *GetMoveRequest) GetGameState() *engine.GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *GetMoveRequest) GetDifficulty() BotDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return BotDifficulty_BOT_DIFFICULTY_UNSPECIFIED
}

func (x *GetMoveRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *GetMoveRequest) GetTimeLimitMs() int32 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

// Response containing the bot's chosen move
type GetMoveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetMoveResponse_Move
	//	*GetMoveResponse_Error
	Result        isGetMoveResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoveResponse) Reset() {
	*x = GetMoveResponse{}
	mi := &file_proto_bot_bot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoveResponse) ProtoMessage() {}

func (x *GetMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_bot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoveResponse.ProtoReflect.Descriptor instead.
func (*GetMoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_bot_bot_proto_rawDescGZIP(), []int{2}
}

func (x *GetMoveResponse) GetResult() isGetMoveResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetMoveResponse) GetMove() *MoveResult {
	if x != nil {
		if x, ok := x.Result.(*GetMoveResponse_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *GetMoveResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetMoveResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetMoveResponse_Result interface {
	isGetMoveResponse_Result()
}

type GetMoveResponse_Move struct {
	Move *MoveResult `protobuf:"bytes,1,opt,name=move,proto3,oneof"`
}

type GetMoveResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetMoveResponse_Move) isGetMoveResponse_Result() {}

func (*GetMoveResponse_Error) isGetMoveResponse_Result() {}

type MoveResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PitIndex        uint32                 `protobuf:"varint,1,opt,name=pit_index,json=pitIndex,proto3" json:"pit_index,omitempty"`                      // The pit the bot chooses to play
	Reasoning       string                 `protobuf:"bytes,2,opt,name=reasoning,proto3" json:"reasoning,omitempty"`                                     // Optional: explanation of why this move was chosen
	EvaluationScore int32                  `protobuf:"varint,3,opt,name=evaluation_score,json=evaluationScore,proto3" json:"evaluation_score,omitempty"` // Optional: bot's evaluation of the position
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MoveResult) Reset() {
	*x = MoveResult{}
	mi := &file_proto_bot_bot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResult) ProtoMessage() {}

func (x *MoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_bot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResult.ProtoReflect.Descriptor instead.
func (*MoveResult) Descriptor() ([]byte, []int) {
	return file_proto_bot_bot_proto_rawDescGZIP(), []int{3}
}

func (x *MoveResult) GetPitIndex() uint32 {
	if x != nil {
		return x.PitIndex
	}
	return 0
}

func (x *MoveResult) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *MoveResult) GetEvaluationScore() int32 {
	if x != nil {
		return x.EvaluationScore
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_bot_bot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_bot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_bot_bot_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Request to list available bots
type ListBotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBotsRequest) Reset() {
	*x = ListBotsRequest{}
	mi := &file_proto_bot_bot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBotsRequest) ProtoMessage() {}

func (x *ListBotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_bot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBotsRequest.ProtoReflect.Descriptor instead.
func (*ListBotsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bot_bot_proto_rawDescGZIP(), []int{5}
}

// Response with available bot profiles
type ListBotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bots          []*BotProfile          `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBotsResponse) Reset() {
	*x = ListBotsResponse{}
	mi := &file_proto_bot_bot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBotsResponse) ProtoMessage() {}

func (x *ListBotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_bot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBotsResponse.ProtoReflect.Descriptor instead.
func (*ListBotsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bot_bot_proto_rawDescGZIP(), []int{6}
}

func (x *ListBotsResponse) GetBots() []*BotProfile {
	if x != nil {
		return x.Bots
	}
	return nil
}

// Request to create a bot player for a game
type CreateBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Difficulty    BotDifficulty          `protobuf:"varint,1,opt,name=difficulty,proto3,enum=proto.bot.BotDifficulty" json:"difficulty,omitempty"`
	NameSuffix    string                 `protobuf:"bytes,2,opt,name=name_suffix,json=nameSuffix,proto3" json:"name_suffix,omitempty"` // Optional: custom suffix for bot name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotRequest) Reset() {
	*x = CreateBotRequest{}
	mi := &file_proto_bot_bot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotRequest) ProtoMessage() {}

func (x *CreateBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_bot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotRequest.ProtoReflect.Descriptor instead.
func (*CreateBotRequest) Descriptor() ([]byte, []int) {
	return file_proto_bot_bot_proto_rawDescGZIP(), []int{7}
}

func (x *CreateBotRequest) GetDifficulty() BotDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return BotDifficulty_BOT_DIFFICULTY_UNSPECIFIED
}

func (x *CreateBotRequest) GetNameSuffix() string {
	if x != nil {
		return x.NameSuffix
	}
	return ""
}

// Response with created bot information
type CreateBotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           *BotProfile            `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotResponse) Reset() {
	*x = CreateBotResponse{}
	mi := &file_proto_bot_bot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotResponse) ProtoMessage() {}

func (x *CreateBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_bot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotResponse.ProtoReflect.Descriptor instead.
func (*CreateBotResponse) Descriptor() ([]byte, []int) {
	return file_proto_bot_bot_proto_rawDescGZIP(), []int{8}
}

func (x *CreateBotResponse) GetBot() *BotProfile {
	if x != nil {
		return x.Bot
	}
	return nil
}

var File_proto_bot_bot_proto protoreflect.FileDescriptor

const file_proto_bot_bot_proto_rawDesc = "" +
	"\n" +
	"\x13proto/bot/bot.proto\x12\tproto.bot\x1a\x19proto/engine/engine.proto\"\xb8\x01\n" +
	"\n" +
	"BotProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\x0e2\x18.proto.bot.BotDifficultyR\n" +
	"difficulty\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04wins\x18\x05 \x01(\x05R\x04wins\x12\x16\n" +
	"\x06losses\x18\x06 \x01(\x05R\x06losses\"\xbd\x01\n" +
	"\x0eGetMoveRequest\x126\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x17.proto.engine.GameStateR\tgameState\x128\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\x0e2\x18.proto.bot.BotDifficultyR\n" +
	"difficulty\x12\x15\n" +
	"\x06bot_id\x18\x03 \x01(\tR\x05botId\x12\"\n" +
	"\rtime_limit_ms\x18\x04 \x01(\x05R\vtimeLimitMs\"r\n" +
	"\x0fGetMoveResponse\x12+\n" +
	"\x04move\x18\x01 \x01(\v2\x15.proto.bot.MoveResultH\x00R\x04move\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\x10.proto.bot.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"r\n" +
	"\n" +
	"MoveResult\x12\x1b\n" +
	"\tpit_index\x18\x01 \x01(\rR\bpitIndex\x12\x1c\n" +
	"\treasoning\x18\x02 \x01(\tR\treasoning\x12)\n" +
	"\x10evaluation_score\x18\x03 \x01(\x05R\x0fevaluationScore\"5\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x11\n" +
	"\x0fListBotsRequest\"=\n" +
	"\x10ListBotsResponse\x12)\n" +
	"\x04bots\x18\x01 \x03(\v2\x15.proto.bot.BotProfileR\x04bots\"m\n" +
	"\x10CreateBotRequest\x128\n" +
	"\n" +
	"difficulty\x18\x01 \x01(\x0e2\x18.proto.bot.BotDifficultyR\n" +
	"difficulty\x12\x1f\n" +
	"\vname_suffix\x18\x02 \x01(\tR\n" +
	"nameSuffix\"<\n" +
	"\x11CreateBotResponse\x12'\n" +
	"\x03bot\x18\x01 \x01(\v2\x15.proto.bot.BotProfileR\x03bot*|\n" +
	"\rBotDifficulty\x12\x1e\n" +
	"\x1aBOT_DIFFICULTY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13BOT_DIFFICULTY_EASY\x10\x01\x12\x19\n" +
	"\x15BOT_DIFFICULTY_MEDIUM\x10\x02\x12\x17\n" +
	"\x13BOT_DIFFICULTY_HARD\x10\x032\xd4\x01\n" +
	"\x03Bot\x12@\n" +
	"\aGetMove\x12\x19.proto.bot.GetMoveRequest\x1a\x1a.proto.bot.GetMoveResponse\x12C\n" +
	"\bListBots\x12\x1a.proto.bot.ListBotsRequest\x1a\x1b.proto.bot.ListBotsResponse\x12F\n" +
	"\tCreateBot\x12\x1b.proto.bot.CreateBotRequest\x1a\x1c.proto.bot.CreateBotResponseB,Z*github.com/laerson/mancala/proto/bot;botpbb\x06proto3"

var (
	file_proto_bot_bot_proto_rawDescOnce sync.Once
	file_proto_bot_bot_proto_rawDescData []byte
)

func file_proto_bot_bot_proto_rawDescGZIP() []byte {
	file_proto_bot_bot_proto_rawDescOnce.Do(func() {
		file_proto_bot_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bot_bot_proto_rawDesc), len(file_proto_bot_bot_proto_rawDesc)))
	})
	return file_proto_bot_bot_proto_rawDescData
}

var file_proto_bot_bot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_bot_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_bot_bot_proto_goTypes = []any{
	(BotDifficulty)(0),        // 0: proto.bot.BotDifficulty
	(*BotProfile)(nil),        // 1: proto.bot.BotProfile
	(*GetMoveRequest)(nil),    // 2: proto.bot.GetMoveRequest
	(*GetMoveResponse)(nil),   // 3: proto.bot.GetMoveResponse
	(*MoveResult)(nil),        // 4: proto.bot.MoveResult
	(*Error)(nil),             // 5: proto.bot.Error
	(*ListBotsRequest)(nil),   // 6: proto.bot.ListBotsRequest
	(*ListBotsResponse)(nil),  // 7: proto.bot.ListBotsResponse
	(*CreateBotRequest)(nil),  // 8: proto.bot.CreateBotRequest
	(*CreateBotResponse)(nil), // 9: proto.bot.CreateBotResponse
	(*engine.GameState)(nil),  // 10: proto.engine.GameState
}
var file_proto_bot_bot_proto_depIdxs = []int32{
	0,  // 0: proto.bot.BotProfile.difficulty:type_name -> proto.bot.BotDifficulty
	10, // 1: proto.bot.GetMoveRequest.game_state:type_name -> proto.engine.GameState
	0,  // 2: proto.bot.GetMoveRequest.difficulty:type_name -> proto.bot.BotDifficulty
	4,  // 3: proto.bot.GetMoveResponse.move:type_name -> proto.bot.MoveResult
	5,  // 4: proto.bot.GetMoveResponse.error:type_name -> proto.bot.Error
	1,  // 5: proto.bot.ListBotsResponse.bots:type_name -> proto.bot.BotProfile
	0,  // 6: proto.bot.CreateBotRequest.difficulty:type_name -> proto.bot.BotDifficulty
	1,  // 7: proto.bot.CreateBotResponse.bot:type_name -> proto.bot.BotProfile
	2,  // 8: proto.bot.Bot.GetMove:input_type -> proto.bot.GetMoveRequest
	6,  // 9: proto.bot.Bot.ListBots:input_type -> proto.bot.ListBotsRequest
	8,  // 10: proto.bot.Bot.CreateBot:input_type -> proto.bot.CreateBotRequest
	3,  // 11: proto.bot.Bot.GetMove:output_type -> proto.bot.GetMoveResponse
	7,  // 12: proto.bot.Bot.ListBots:output_type -> proto.bot.ListBotsResponse
	9,  // 13: proto.bot.Bot.CreateBot:output_type -> proto.bot.CreateBotResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_bot_bot_proto_init() }
func file_proto_bot_bot_proto_init() {
	if File_proto_bot_bot_proto != nil {
		return
	}
	file_proto_bot_bot_proto_msgTypes[2].OneofWrappers = []any{
		(*GetMoveResponse_Move)(nil),
		(*GetMoveResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bot_bot_proto_rawDesc), len(file_proto_bot_bot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bot_bot_proto_goTypes,
		DependencyIndexes: file_proto_bot_bot_proto_depIdxs,
		EnumInfos:         file_proto_bot_bot_proto_enumTypes,
		MessageInfos:      file_proto_bot_bot_proto_msgTypes,
	}.Build()
	File_proto_bot_bot_proto = out.File
	file_proto_bot_bot_proto_goTypes = nil
	file_proto_bot_bot_proto_depIdxs = nil
}
