name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push engine image
        uses: docker/build-push-action@v6
        with:
          file: ./cmd/engine/Dockerfile
          push: true
          tags: ghcr.io/laerson/mancala:latest-engine

      - name: Build and push games image
        uses: docker/build-push-action@v6
        with:
          file: ./cmd/games/Dockerfile
          push: true
          tags: ghcr.io/laerson/mancala:latest-games